import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Green Vision title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <title>Green Vision</title>
      <meta name="description" content="This is a description of my page." />
      <meta name="keywords" content="my, page, keywords" />
      <meta name="robots" content="index, follow" />
      <meta name="author" content="M Awais" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center ">
          <Navbar/>
        </div>
        {children}
      </body>
    </html>
  );
}
